language: node_js
cache:
directories:
- node_modules
notifications:
email: false
node_js:
- '7'
branches:
except:
- /^v\d+\.\d+\.\d+$/
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> travis ok

sudo: required
dist: trusty
addons:
  sauce_connect: true
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
<<<<<<< HEAD
=======
>>>>>>> add travis
=======
>>>>>>> travis ok
