language: node_js
cache:
directories:
  - node_modules
notifications:
email: false
node_js:
  - '8'
branches:
except:
  - /^v\d+\.\d+\.\d+$/

sudo: required
dist: trusty
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
    - stty cols 80

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
